---
go_carbon_used_cron_daemon: "{{ 'cron' if ansible_os_family | lower == 'debian' else 'cronie' }}"

go_carbon_storage_schema:
  icinga2:
    # 1 Host and 1 Metric produce: 556.94 Kilobytes
    pattern: '^icinga2\.'
    retentions: '1m:15d,5m:30d,15m:120d,1h:240d'
