---

mariadb_databases:
  - name: monitoring
    collation: utf8mb4_bin
    encoding: utf8mb4

  # content-management-server
  - name: cm_management
    collation: utf8mb4_bin
    encoding: utf8mb4

  # caefeeder-preview
  - name: cm_mcaefeeder
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:

  - name: monitoring
    host: "%"
    password: monitoring
    priv: "monitoring.*:ALL"

  # content-management-server
  - name: cm_management
    host: "%"
    password: "{{ vault__cm_management }}"
    priv: "cm_management.*:ALL"

  # caefeeder-preview
  - name: cm_mcaefeeder
    host: "%"
    password: "{{ vault__cm_mcaefeeder }}"
    priv: "cm_mcaefeeder.*:ALL"
