---

mariadb_bind_address: "{{ ansible_default_ipv4.address }}"
mariadb_root_password: secr3t

mariadb_databases:
  - name: monitoring
    collation: utf8mb4_bin
    encoding: utf8mb4

mariadb_users:

  - name: monitoring
    host: "%"
    password: monitoring
    priv: "monitoring.*:ALL"
