---

icingaweb_users:
  admin:
    password: admin
  bodsch:
    password: 12345


icingaweb_resources:
  db:
    icingaweb:
      type: db
      db: mysql
      host: 192.168.130.10
      port: 3306
      dbname: "{{ icingaweb_auth_dba_database }}"
      username: "{{ icingaweb_auth_dba_username }}"
      password: "{{ icingaweb_auth_dba_password }}"
      prefix: icingaweb_
      charset: utf8

    icinga_ido:
      type: db
      db: mysql
      host: 192.168.130.10
      port: 3306
      dbname: "{{ icinga2_ido_database }}"
      username: "{{ icinga2_ido_username }}"
      password: "{{ icinga2_ido_password }}"
      charset: utf8

icingaweb_auth_backend: "{{ icingaweb_resources.db.icingaweb }}"

icingaweb_commandtransport:
  master-1:
    transport: api
    host: 192.168.130.20
    port: 5665
    username: icingaweb
    password: S0mh1TuFJI
#  master-2:
#    transport: api
#    host: 192.168.130.21
#    port: 5665
#    username: icingaweb
#    password: S0mh1TuFJI

icingaweb_external_modules:
  - grafana:
    enabled: true
    name: grafana
    src: https://github.com/Mikesch-mp/icingaweb2-module-grafana.git
    version: v1.3.6
    configuration:
      # support_grafana_5: false
      host: tsdb.icinga.local
      debug: false
      enableLink: true
      defaultdashboard:
        name: base-metrics
        uid: Z-TfDRpGz
    graphs:
      - graph: ping4
        dashboard: "hostalive"
        panelId: "9"
        orgId: "1"
        repeatable: "no"
        dashboarduid: "Z-TfDRpGz"
      - graph: hostalive
        dashboard: "hostalive"
        panelId: "9"
        orgId: "1"
        repeatable: "no"
        dashboarduid: "Z-TfDRpGz"
      - graph: load
        dashboard: "load"
        panelId: 4
        orgId: 2
        repeatable: false
        dashboarduid: "Z-TfDRpGz"
