---

icingaweb_users:
  - admin:
    username: admin
    password: admin
    # force: true
    preferences:
      language: de_DE
      timezone: Europe/Berlin
      show_application_state_messages: false
      show_stacktraces: false
      show_benchmark: false
      auto_refresh: true
  - bodsch:
    username: bodsch
    password: bodsch

icingaweb_log_level: WARN

icingaweb_resources:
  icingaweb:
    type: db
    db: mysql
    host: 192.168.130.10
    port: 3306
    dbname: "{{ icingaweb_auth_dba_database }}"
    username: "{{ icingaweb_auth_dba_username }}"
    password: "{{ icingaweb_auth_dba_password }}"
    prefix: icingaweb_
    charset: utf8
  icinga_ido:
    type: db
    db: mysql
    host: 192.168.130.10
    port: 3306
    dbname: "{{ icinga2_ido_database }}"
    username: "{{ icinga2_ido_username }}"
    password: "{{ icinga2_ido_password }}"
    charset: utf8

# icingaweb_authentication:
#   azure_users:
#     backend: "msldap"
#     resource: "azure_ad"
#     # login per full email:
#     #   userPrincipalName
#     # login per user (emailname without domain part)
#     #   sAMAccountName
#     user_name_attribute: "userPrincipalName"
#     filter: "(|(memberOf=CN=svc_icinga_viewer,DC=foo,DC=bar)(memberOf=CN=svc_icinga_admin,DC=foo,DC=bar))"

icingaweb_auth_backend:
  database:
    host: 192.168.130.10
    port: 3306
    dbname: "{{ icingaweb_auth_dba_database }}"
    username: "{{ icingaweb_auth_dba_username }}"
    password: "{{ icingaweb_auth_dba_password }}"

icingaweb_roles:
  - name: 'local admins'
    users:
      - admin
      - bodsch
    permissions: '*'

icingaweb_groups:
  ldap_groups:
    backend: "ldap" # msldap
    resource: "ldap"
    user_backend: "auth_ldap"
    base_dn: "dc=ldap,dc=icinga,dc=local"
    group_class: "*"
    group_name_attribute: "gid"
    group_member_attribute: "memberUid"

icingaweb_commandtransport:
  master-1:
    transport: api
    host: 192.168.130.20
    port: 5665
    username: icingaweb
    password: S0mh1TuFJI
  # master-2:
  #   transport: api
  #   host: 192.168.130.21
  #   port: 5665
  #   username: icingaweb
  #   password: S0mh1TuFJI

icinga2_api:
  user:
    icingaweb:
      password: S0mh1TuFJI

icingaweb_external_modules:
  - graphite:
    enabled: true
    name: graphite
    src: https://github.com/Icinga/icingaweb2-module-graphite.git
    version: v1.1.0
    # url: https://github.com/Icinga/icingaweb2-module-graphite/archive/v1.1.0.zip
    configuration:
      host: http://tsdb.icinga.local
      port: 8088
      ui:
        default_time_range: 12
        default_time_range_unit: hours
      # advanced:
      #   # graphite_writer_host_name_template: host.tpl
      #   # graphite_writer_service_name_template: ''
      #   # customvar_obscured_check_command: ''

  - grafana:
    enabled: false
    name: grafana
    src: https://github.com/Mikesch-mp/icingaweb2-module-grafana.git
    version: v1.3.6
    configuration:
      # support_grafana_5: false
      host: tsdb.icinga.local
      debug: false
      enableLink: true
      defaultdashboard:
        name: base-metrics
        uid: Z-TfDRpGz
    graphs:
      - graph: ping4
        dashboard: "hostalive"
        panelId: "9"
        orgId: "1"
        repeatable: "no"
        dashboarduid: "Z-TfDRpGz"
      - graph: hostalive
        dashboard: "hostalive"
        panelId: "9"
        orgId: "1"
        repeatable: "no"
        dashboarduid: "Z-TfDRpGz"
      - graph: load
        dashboard: "load"
        panelId: 4
        orgId: 2
        repeatable: false
        dashboarduid: "Z-TfDRpGz"
