---

- name: ensure needed packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    "{{ additional_packages }}"

- include_tasks: fqdn.yml

- name: set timezone to UTC
  timezone:
    name: Etc/UTC

- name: Make sure Ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add subdomains to /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: change bash_profile
  template:
    src: bash_profile.j2
    dest: /root/.bash_profile

- name: ensure unneeded services are stopped and disabled
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  ignore_errors: true
  no_log: true
  loop:
    "{{ unneeded_services }}"
