---

icinga2_mode: master

# both masters use on IDO connection
icinga2_ido_host: '192.168.130.10'

icinga2_api_user:
  icinga2:
    password: S0mh1TuFJI
    permissions: '*'

  icingaweb:
    password: S0mh1TuFJI
    permissions:
      - "status/query"
      - "actions/*"
      - "objects/modify/*"
      - "objects/query/*"


# icinga2_mainlog_severity: information

icinga2_master_features_enabled:
  - checker
  - api
  - ido-mysql
  - mainlog

