---

- hosts: all
  gather_facts: true
  become: true
  remote_user: ansible
  environment:
    NETRC: ''
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  pre_tasks:

    - debug:
        msg:
          - "os_family                  : {{ ansible_os_family }}"
          - "distribution               : {{ ansible_distribution }}"
          - "distribution_major_version : {{ ansible_distribution_major_version }}"
          - "version                    : {{ ansible_version.full }}"
          - "python_version             : {{ ansible_python.version.major }}"

    # Disable SELinux
    - selinux:
        state: disabled

    - name: Set SELinux in permissive mode until the machine is rebooted
      command: setenforce 0
      ignore_errors: true
      changed_when: false

  roles:
    - role: sshd
    - role: common
    # - role: ulimit
    - role: chrony
    - role: dnsmasq
    - role: resolv

# prepare the databases
- hosts: databases
  gather_facts: true
  become: true
  remote_user: ansible
  environment:
    NETRC: ''
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  roles:
    - role: mariadb


- hosts: all
  gather_facts: true
  become: true
  remote_user: ansible
  roles:
    - role: monitoring-plugins
