---

- hosts: tsdb
  gather_facts: true
  become: true
  remote_user: ansible
  environment:
    NETRC: ''
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"

  tasks:

    - name: Testing variables with SUDO=NO
      block:
      #hosts: "master-1.icinga.local"
      #sudo: no

      # tasks:
        - name: "PLAYBOOK SUDO=NO, TASK SUDO=NO"
          command: whoami
          register: whoami_output
          sudo: no
        - debug: var=whoami_output.stdout
        - debug: var=ansible_ssh_user
          sudo: no
        - debug: var=ansible_user_id
          sudo: no

        - name: "PLAYBOOK SUDO=NO, TASK SUDO=YES"
          command: whoami
          register: whoami_output
          sudo: yes
        - debug: var=whoami_output.stdout
        - debug: var=ansible_ssh_user
          sudo: yes
        - debug: var=ansible_user_id
          sudo: yes

    - name: Testing variables with SUDO=YES
      block:
      #hosts: "master-1.icinga.local"
      #sudo: yes

      #tasks:
        - name: "PLAYBOOK SUDO=YES, TASK SUDO=NO"
          command: whoami
          register: whoami_output
          sudo: no
        - debug: var=whoami_output.stdout
        - debug: var=ansible_ssh_user
          sudo: no
        - debug: var=ansible_user_id
          sudo: no

        - name: "PLAYBOOK SUDO=YES, TASK SUDO=YES"
          command: whoami
          register: whoami_output
          sudo: yes
        - debug: var=whoami_output.stdout
        - debug: var=ansible_ssh_user
          sudo: yes
        - debug: var=ansible_user_id
          sudo: yes


# OUTPUT (condensed):

# PLAY [Testing variables with SUDO=NO] *****************************************

# TASK: [PLAYBOOK SUDO=NO, TASK SUDO=NO] ****************************************
# "whoami_output.stdout": "vagrant"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "vagrant"
#
# TASK: [PLAYBOOK SUDO=NO, TASK SUDO=YES] ***************************************
# "whoami_output.stdout": "root"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "vagrant"


# PLAY [Testing variables with SUDO=YES] ****************************************

# GATHERING FACTS ***************************************************************
# TASK: [PLAYBOOK SUDO=YES, TASK SUDO=NO] ***************************************
# "whoami_output.stdout": "vagrant"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "root"
#
# TASK: [PLAYBOOK SUDO=YES, TASK SUDO=YES] **************************************
# "whoami_output.stdout": "root"
# "ansible_ssh_user": "vagrant"
# "ansible_user_id": "root"
